export interface RecipeIngredient {
  name: string;
  amount: number;
  unit: string;
  category: string;
  isPantryStaple: boolean;
}

export interface RecipeVariation {
  day: number;
  suggestion: string;
  extraIngredients?: string[];
}

export interface Recipe {
  id: string;
  name: string;
  description: string;
  servings: number;
  prepTime: number;
  cookTime: number;
  batchCookingScore: number;
  freezerFriendly: boolean;
  fridgeLifeDays: number;
  freezerLifeMonths: number;
  imageUrl?: string;
  ingredients: RecipeIngredient[];
  instructions: string[];
  variations: RecipeVariation[];
  tags: string[];
}

export const recipes: Recipe[] = [
  {
    id: 'chili-con-carne',
    name: 'Chili con Carne',
    description: 'Klassieke Mexicaanse stoofschotel, perfect voor batch cooking. Lekker met rijst, tortilla\'s of over gebakken aardappelen.',
    servings: 8,
    prepTime: 20,
    cookTime: 60,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 5,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'rundergehakt', amount: 500, unit: 'gram', category: 'vlees', isPantryStaple: false },
      { name: 'ui', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: true },
      { name: 'knoflook', amount: 3, unit: 'tenen', category: 'groenten', isPantryStaple: true },
      { name: 'paprika', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: false },
      { name: 'kidneybonen', amount: 400, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'tomatenblokjes', amount: 800, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'tomatenpuree', amount: 2, unit: 'el', category: 'conserven', isPantryStaple: true },
      { name: 'komijn', amount: 2, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'paprikapoeder', amount: 1, unit: 'el', category: 'kruiden', isPantryStaple: true },
      { name: 'chilivlokken', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
    ],
    instructions: [
      'Snipper de ui en hak de knoflook fijn. Snijd de paprika\'s in blokjes.',
      'Bak het gehakt in een grote pan op hoog vuur tot het bruin is. Breek het goed uit elkaar.',
      'Voeg de ui en knoflook toe en bak 3 minuten mee.',
      'Voeg de paprika, tomatenpuree en alle kruiden toe. Bak 2 minuten.',
      'Giet de tomatenblokjes en kidneybonen (uitgelekt) erbij.',
      'Breng aan de kook, zet het vuur laag en laat 45-60 minuten sudderen.',
      'Proef en breng op smaak met zout en peper.',
    ],
    variations: [
      { day: 1, suggestion: 'Serveer met rijst en geraspte kaas', extraIngredients: ['rijst', 'kaas'] },
      { day: 2, suggestion: 'Maak nacho\'s met tortillachips', extraIngredients: ['tortillachips', 'zure room'] },
      { day: 3, suggestion: 'Vul taco shells of wraps', extraIngredients: ['tacoschelpen', 'ijsbergsla'] },
      { day: 4, suggestion: 'Over gebakken aardappelen', extraIngredients: ['aardappelen'] },
    ],
    tags: ['Mexicaans', 'gehakt', 'stoofschotel', 'budget', 'invriezen'],
  },
  {
    id: 'bolognese-saus',
    name: 'Bolognese Saus',
    description: 'Rijke Italiaanse vleessaus. Maak een grote pan en gebruik voor pasta, lasagne of gevulde paprika\'s.',
    servings: 10,
    prepTime: 20,
    cookTime: 90,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 5,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'rundergehakt', amount: 500, unit: 'gram', category: 'vlees', isPantryStaple: false },
      { name: 'ui', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: true },
      { name: 'wortel', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: false },
      { name: 'bleekselderij', amount: 2, unit: 'stengels', category: 'groenten', isPantryStaple: false },
      { name: 'knoflook', amount: 3, unit: 'tenen', category: 'groenten', isPantryStaple: true },
      { name: 'tomatenblokjes', amount: 800, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'tomatenpuree', amount: 3, unit: 'el', category: 'conserven', isPantryStaple: true },
      { name: 'rode wijn', amount: 150, unit: 'ml', category: 'dranken', isPantryStaple: false },
      { name: 'oregano', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'laurierblad', amount: 2, unit: 'stuks', category: 'kruiden', isPantryStaple: true },
    ],
    instructions: [
      'Snipper de ui fijn. Rasp of snijd de wortel en bleekselderij zeer fijn.',
      'Bak het gehakt in een grote pan tot bruin en gaar.',
      'Voeg ui, wortel en selderij toe. Bak 8-10 minuten tot zacht.',
      'Voeg knoflook en tomatenpuree toe, bak 2 minuten.',
      'Schenk de rode wijn erbij en laat grotendeels verdampen.',
      'Voeg tomatenblokjes, oregano en laurierblad toe.',
      'Laat 1-1,5 uur zachtjes sudderen. Roer af en toe.',
      'Verwijder laurierblad en breng op smaak.',
    ],
    variations: [
      { day: 1, suggestion: 'Klassiek met spaghetti en Parmezaan', extraIngredients: ['spaghetti', 'Parmezaanse kaas'] },
      { day: 2, suggestion: 'Maak lasagne met bechamelsaus', extraIngredients: ['lasagnevellen', 'bechamelsaus', 'kaas'] },
      { day: 3, suggestion: 'Gevulde paprika\'s', extraIngredients: ['paprika', 'rijst', 'kaas'] },
      { day: 4, suggestion: 'Over rigatoni of penne', extraIngredients: ['penne'] },
    ],
    tags: ['Italiaans', 'gehakt', 'pasta', 'klassieker', 'invriezen'],
  },
  {
    id: 'kipkerrie',
    name: 'Kipkerrie',
    description: 'Romige Indiase kipkerrie met groenten. Snel klaar en perfect om in grote hoeveelheden te maken.',
    servings: 6,
    prepTime: 15,
    cookTime: 35,
    batchCookingScore: 4,
    freezerFriendly: true,
    fridgeLifeDays: 4,
    freezerLifeMonths: 2,
    ingredients: [
      { name: 'kipfilet', amount: 600, unit: 'gram', category: 'vlees', isPantryStaple: false },
      { name: 'ui', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: true },
      { name: 'knoflook', amount: 3, unit: 'tenen', category: 'groenten', isPantryStaple: true },
      { name: 'gember', amount: 2, unit: 'cm', category: 'groenten', isPantryStaple: false },
      { name: 'tomatenblokjes', amount: 400, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'kokosmelk', amount: 400, unit: 'ml', category: 'conserven', isPantryStaple: false },
      { name: 'kerriepoeder', amount: 2, unit: 'el', category: 'kruiden', isPantryStaple: true },
      { name: 'kurkuma', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'garam masala', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'spinazie', amount: 200, unit: 'gram', category: 'groenten', isPantryStaple: false },
    ],
    instructions: [
      'Snijd de kipfilet in blokjes. Snipper de ui, hak knoflook en rasp gember.',
      'Bak de kip in batches goudbruin. Zet apart.',
      'Fruit de ui tot glazig. Voeg knoflook en gember toe.',
      'Voeg alle specerijen toe en bak 1 minuut.',
      'Giet de tomatenblokjes en kokosmelk erbij.',
      'Breng aan de kook en voeg de kip terug.',
      'Laat 20 minuten sudderen tot de kip gaar is.',
      'Roer op het laatst de spinazie erdoor tot geslonken.',
    ],
    variations: [
      { day: 1, suggestion: 'Met basmatirijst', extraIngredients: ['basmatirijst'] },
      { day: 2, suggestion: 'Met naanbrood en raita', extraIngredients: ['naanbrood', 'yoghurt', 'komkommer'] },
      { day: 3, suggestion: 'Over couscous', extraIngredients: ['couscous'] },
      { day: 4, suggestion: 'Met roti of chapati', extraIngredients: ['roti'] },
    ],
    tags: ['Indiaas', 'kip', 'kerrie', 'romig', 'invriezen'],
  },
  {
    id: 'linzensoep',
    name: 'Linzensoep',
    description: 'Voedzame en goedkope linzensoep. Vol eiwitten en vezels, perfect voor de koude maanden.',
    servings: 8,
    prepTime: 15,
    cookTime: 45,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 6,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'rode linzen', amount: 400, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'ui', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: true },
      { name: 'wortel', amount: 3, unit: 'stuks', category: 'groenten', isPantryStaple: false },
      { name: 'knoflook', amount: 4, unit: 'tenen', category: 'groenten', isPantryStaple: true },
      { name: 'tomatenblokjes', amount: 400, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'groentebouillon', amount: 1.5, unit: 'liter', category: 'bouillon', isPantryStaple: true },
      { name: 'komijn', amount: 2, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'kurkuma', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'citroensap', amount: 2, unit: 'el', category: 'kruiden', isPantryStaple: true },
    ],
    instructions: [
      'Snipper de ui en hak de knoflook. Snijd wortels in kleine stukjes.',
      'Fruit de ui in olie tot glazig.',
      'Voeg knoflook, komijn en kurkuma toe. Bak 1 minuut.',
      'Voeg wortels, linzen en tomatenblokjes toe.',
      'Schenk de bouillon erbij en breng aan de kook.',
      'Laat 35-40 minuten zachtjes koken tot linzen zacht zijn.',
      'Pureer gedeeltelijk voor een romige textuur.',
      'Breng op smaak met citroensap, zout en peper.',
    ],
    variations: [
      { day: 1, suggestion: 'Met knapperig brood', extraIngredients: ['brood'] },
      { day: 2, suggestion: 'Getopt met yoghurt en verse kruiden', extraIngredients: ['yoghurt', 'koriander'] },
      { day: 3, suggestion: 'Met gebakken spekjes', extraIngredients: ['spek'] },
    ],
    tags: ['vegetarisch', 'soep', 'linzen', 'budget', 'gezond'],
  },
  {
    id: 'stamppot-boerenkool',
    name: 'Stamppot Boerenkool',
    description: 'Klassieke Nederlandse winterkost. Vullend, voedzaam en goedkoop te maken.',
    servings: 4,
    prepTime: 15,
    cookTime: 30,
    batchCookingScore: 3,
    freezerFriendly: false,
    fridgeLifeDays: 3,
    freezerLifeMonths: 0,
    ingredients: [
      { name: 'aardappelen', amount: 1000, unit: 'gram', category: 'groenten', isPantryStaple: false },
      { name: 'boerenkool', amount: 500, unit: 'gram', category: 'groenten', isPantryStaple: false },
      { name: 'rookworst', amount: 300, unit: 'gram', category: 'vlees', isPantryStaple: false },
      { name: 'melk', amount: 100, unit: 'ml', category: 'zuivel', isPantryStaple: true },
      { name: 'boter', amount: 50, unit: 'gram', category: 'zuivel', isPantryStaple: true },
      { name: 'mosterd', amount: 2, unit: 'el', category: 'sauzen', isPantryStaple: true },
    ],
    instructions: [
      'Schil de aardappelen en snijd in gelijke stukken.',
      'Kook de aardappelen in gezouten water in 20 minuten gaar.',
      'Verwarm de rookworst volgens de verpakking.',
      'Giet de aardappelen af, bewaar wat kookvocht.',
      'Stamp de aardappelen met melk en boter.',
      'Roer de boerenkool erdoor (eventueel kort opwarmen).',
      'Voeg kookvocht toe voor gewenste consistentie.',
      'Serveer met rookworst en mosterd.',
    ],
    variations: [
      { day: 1, suggestion: 'Klassiek met rookworst en jus', extraIngredients: ['jus'] },
      { day: 2, suggestion: 'Met gebakken spekjes', extraIngredients: ['spek'] },
      { day: 3, suggestion: 'Restjes als stamppotballetjes bakken', extraIngredients: ['paneermeel', 'ei'] },
    ],
    tags: ['Nederlands', 'stamppot', 'winter', 'traditioneel'],
  },
  {
    id: 'gehaktballetjes-tomatensaus',
    name: 'Gehaktballetjes in Tomatensaus',
    description: 'Sappige gehaktballetjes in rijke tomatensaus. Lekker met pasta, brood of rijst.',
    servings: 6,
    prepTime: 25,
    cookTime: 40,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 4,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'half-om-half gehakt', amount: 500, unit: 'gram', category: 'vlees', isPantryStaple: false },
      { name: 'ui', amount: 1, unit: 'stuk', category: 'groenten', isPantryStaple: true },
      { name: 'knoflook', amount: 2, unit: 'tenen', category: 'groenten', isPantryStaple: true },
      { name: 'ei', amount: 1, unit: 'stuk', category: 'zuivel', isPantryStaple: true },
      { name: 'paneermeel', amount: 50, unit: 'gram', category: 'bakken', isPantryStaple: true },
      { name: 'tomatenblokjes', amount: 800, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'tomatenpuree', amount: 2, unit: 'el', category: 'conserven', isPantryStaple: true },
      { name: 'oregano', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'basilicum', amount: 1, unit: 'el', category: 'kruiden', isPantryStaple: true },
    ],
    instructions: [
      'Meng gehakt met fijngehakte ui, ei en paneermeel. Kruid met zout en peper.',
      'Draai 20-24 balletjes van het mengsel.',
      'Bak de balletjes rondom bruin in olie. Zet apart.',
      'Fruit knoflook in dezelfde pan.',
      'Voeg tomatenblokjes, tomatenpuree en kruiden toe.',
      'Laat 10 minuten inkoken.',
      'Leg de gehaktballetjes in de saus.',
      'Laat nog 20 minuten zachtjes sudderen.',
    ],
    variations: [
      { day: 1, suggestion: 'Met spaghetti', extraIngredients: ['spaghetti', 'Parmezaanse kaas'] },
      { day: 2, suggestion: 'In een broodje (meatball sub)', extraIngredients: ['stokbrood', 'kaas'] },
      { day: 3, suggestion: 'Met rijst', extraIngredients: ['rijst'] },
      { day: 4, suggestion: 'Met aardappelpuree', extraIngredients: ['aardappelen', 'melk', 'boter'] },
    ],
    tags: ['Italiaans', 'gehakt', 'tomatensaus', 'comfort food'],
  },
  {
    id: 'minestrone',
    name: 'Minestrone',
    description: 'Rijke Italiaanse groentesoep met pasta en bonen. Een maaltijd op zich.',
    servings: 8,
    prepTime: 20,
    cookTime: 45,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 5,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'ui', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: true },
      { name: 'wortel', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: false },
      { name: 'bleekselderij', amount: 2, unit: 'stengels', category: 'groenten', isPantryStaple: false },
      { name: 'courgette', amount: 1, unit: 'stuk', category: 'groenten', isPantryStaple: false },
      { name: 'knoflook', amount: 3, unit: 'tenen', category: 'groenten', isPantryStaple: true },
      { name: 'tomatenblokjes', amount: 400, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'witte bonen', amount: 400, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'groentebouillon', amount: 1.5, unit: 'liter', category: 'bouillon', isPantryStaple: true },
      { name: 'kleine pasta', amount: 100, unit: 'gram', category: 'pasta-rijst', isPantryStaple: false },
      { name: 'spinazie', amount: 100, unit: 'gram', category: 'groenten', isPantryStaple: false },
    ],
    instructions: [
      'Snijd alle groenten in kleine blokjes.',
      'Fruit ui, wortel en selderij in olie tot zacht.',
      'Voeg knoflook en courgette toe, bak 2 minuten.',
      'Voeg tomatenblokjes, bonen en bouillon toe.',
      'Breng aan de kook en laat 25 minuten sudderen.',
      'Voeg pasta toe en kook nog 10 minuten.',
      'Roer de spinazie erdoor.',
      'Serveer met Parmezaanse kaas en brood.',
    ],
    variations: [
      { day: 1, suggestion: 'Met knapperig Italiaans brood', extraIngredients: ['ciabatta'] },
      { day: 2, suggestion: 'Met pesto-topping', extraIngredients: ['pesto'] },
      { day: 3, suggestion: 'Met extra Parmezaan', extraIngredients: ['Parmezaanse kaas'] },
    ],
    tags: ['Italiaans', 'vegetarisch', 'soep', 'groenten', 'pasta'],
  },
  {
    id: 'dhal',
    name: 'Dhal (Indiase Linzencurry)',
    description: 'Romige Indiase linzencurry. Zeer voordelig, vol eiwitten en smaakvol.',
    servings: 6,
    prepTime: 10,
    cookTime: 35,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 5,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'rode linzen', amount: 300, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'ui', amount: 1, unit: 'stuk', category: 'groenten', isPantryStaple: true },
      { name: 'knoflook', amount: 3, unit: 'tenen', category: 'groenten', isPantryStaple: true },
      { name: 'gember', amount: 2, unit: 'cm', category: 'groenten', isPantryStaple: false },
      { name: 'tomatenblokjes', amount: 400, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'kokosmelk', amount: 200, unit: 'ml', category: 'conserven', isPantryStaple: false },
      { name: 'kurkuma', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'komijn', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'garam masala', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'koriander', amount: 2, unit: 'el', category: 'kruiden', isPantryStaple: false },
    ],
    instructions: [
      'Fruit gesnipperde ui tot goudbruin.',
      'Voeg knoflook, gember en alle specerijen toe.',
      'Bak 1 minuut tot het geurt.',
      'Voeg linzen, tomaten en 500ml water toe.',
      'Kook 25 minuten tot linzen zacht zijn.',
      'Roer kokosmelk erdoor.',
      'Breng op smaak en garneer met koriander.',
    ],
    variations: [
      { day: 1, suggestion: 'Met basmatirijst', extraIngredients: ['rijst'] },
      { day: 2, suggestion: 'Met naanbrood', extraIngredients: ['naanbrood'] },
      { day: 3, suggestion: 'Met chapati en raita', extraIngredients: ['chapati', 'yoghurt'] },
    ],
    tags: ['Indiaas', 'vegan', 'linzen', 'curry', 'budget'],
  },
  {
    id: 'pulled-pork',
    name: 'Pulled Pork',
    description: 'Langzaam gegaarde pulled pork. Bereid een grote hoeveelheid en gebruik de hele week.',
    servings: 12,
    prepTime: 20,
    cookTime: 360,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 5,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'varkensschouder', amount: 2000, unit: 'gram', category: 'vlees', isPantryStaple: false },
      { name: 'ui', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: true },
      { name: 'knoflook', amount: 6, unit: 'tenen', category: 'groenten', isPantryStaple: true },
      { name: 'paprikapoeder', amount: 2, unit: 'el', category: 'kruiden', isPantryStaple: true },
      { name: 'komijn', amount: 1, unit: 'el', category: 'kruiden', isPantryStaple: true },
      { name: 'bruine suiker', amount: 3, unit: 'el', category: 'bakken', isPantryStaple: true },
      { name: 'tomatenketchup', amount: 200, unit: 'ml', category: 'sauzen', isPantryStaple: true },
      { name: 'appelazijn', amount: 4, unit: 'el', category: 'zuur', isPantryStaple: true },
      { name: 'worcestershiresaus', amount: 2, unit: 'el', category: 'sauzen', isPantryStaple: true },
    ],
    instructions: [
      'Meng alle droge kruiden en wrijf het vlees ermee in.',
      'Leg het vlees in een braadpan met gesneden uien eronder.',
      'Meng ketchup, azijn, worcestershiresaus en 200ml water.',
      'Giet over het vlees.',
      'Braad afgedekt 6 uur op 150°C of tot het uit elkaar valt.',
      'Trek het vlees uit elkaar met twee vorken.',
      'Meng met het braadvocht.',
    ],
    variations: [
      { day: 1, suggestion: 'In broodjes met coleslaw', extraIngredients: ['broodjes', 'coleslaw'] },
      { day: 2, suggestion: 'Taco\'s met avocado', extraIngredients: ['tacoschelpen', 'avocado', 'koriander'] },
      { day: 3, suggestion: 'Op rijst met kimchi', extraIngredients: ['rijst', 'kimchi'] },
      { day: 4, suggestion: 'In wraps met kaas', extraIngredients: ['wraps', 'kaas'] },
      { day: 5, suggestion: 'Op pizza', extraIngredients: ['pizzabodem', 'mozzarella'] },
    ],
    tags: ['Amerikaans', 'varkensvlees', 'slow cooking', 'BBQ'],
  },
  {
    id: 'groentecurry',
    name: 'Groentecurry',
    description: 'Kleurrijke vegetarische curry vol groenten. Snel klaar en vol smaak.',
    servings: 6,
    prepTime: 15,
    cookTime: 25,
    batchCookingScore: 4,
    freezerFriendly: true,
    fridgeLifeDays: 4,
    freezerLifeMonths: 2,
    ingredients: [
      { name: 'ui', amount: 1, unit: 'stuk', category: 'groenten', isPantryStaple: true },
      { name: 'paprika', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: false },
      { name: 'courgette', amount: 1, unit: 'stuk', category: 'groenten', isPantryStaple: false },
      { name: 'bloemkool', amount: 300, unit: 'gram', category: 'groenten', isPantryStaple: false },
      { name: 'kikkererwten', amount: 400, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'kokosmelk', amount: 400, unit: 'ml', category: 'conserven', isPantryStaple: false },
      { name: 'currypasta', amount: 3, unit: 'el', category: 'sauzen', isPantryStaple: false },
      { name: 'knoflook', amount: 2, unit: 'tenen', category: 'groenten', isPantryStaple: true },
      { name: 'gember', amount: 2, unit: 'cm', category: 'groenten', isPantryStaple: false },
    ],
    instructions: [
      'Snijd alle groenten in hapklare stukken.',
      'Fruit ui, knoflook en gember.',
      'Voeg currypasta toe en bak 1 minuut.',
      'Voeg bloemkool en paprika toe.',
      'Giet kokosmelk erbij en voeg kikkererwten toe.',
      'Laat 15 minuten sudderen.',
      'Voeg courgette toe laatste 5 minuten.',
      'Breng op smaak en serveer.',
    ],
    variations: [
      { day: 1, suggestion: 'Met jasmijnrijst', extraIngredients: ['jasmijnrijst'] },
      { day: 2, suggestion: 'Met naanbrood', extraIngredients: ['naanbrood'] },
      { day: 3, suggestion: 'Over noedels', extraIngredients: ['noedels'] },
    ],
    tags: ['vegetarisch', 'curry', 'Aziatisch', 'gezond'],
  },
  {
    id: 'erwtensoep',
    name: 'Erwtensoep',
    description: 'Traditionele Nederlandse split erwtensoep met rookworst. De dag erna nog lekkerder!',
    servings: 10,
    prepTime: 20,
    cookTime: 120,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 6,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'spliterwten', amount: 500, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'rookworst', amount: 300, unit: 'gram', category: 'vlees', isPantryStaple: false },
      { name: 'prei', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: false },
      { name: 'wortel', amount: 3, unit: 'stuks', category: 'groenten', isPantryStaple: false },
      { name: 'bleekselderij', amount: 3, unit: 'stengels', category: 'groenten', isPantryStaple: false },
      { name: 'aardappelen', amount: 300, unit: 'gram', category: 'groenten', isPantryStaple: false },
      { name: 'spek', amount: 150, unit: 'gram', category: 'vlees', isPantryStaple: false },
      { name: 'laurierblad', amount: 2, unit: 'stuks', category: 'kruiden', isPantryStaple: true },
    ],
    instructions: [
      'Week de spliterwten minimaal 12 uur.',
      'Kook de erwten met 2,5 liter water en laurier.',
      'Voeg na 30 minuten het spek toe.',
      'Snijd alle groenten en voeg toe na 1 uur.',
      'Kook nog 1 uur tot erwten zacht zijn.',
      'Voeg rookworst toe laatste 20 minuten.',
      'Haal spek en worst eruit, snijd in plakjes.',
      'Serveer soep met plakjes worst en spek.',
    ],
    variations: [
      { day: 1, suggestion: 'Met roggebrood en boter', extraIngredients: ['roggebrood', 'boter'] },
      { day: 2, suggestion: 'Extra dik, als stamppot', extraIngredients: [] },
      { day: 3, suggestion: 'Met katenspek', extraIngredients: ['katenspek'] },
    ],
    tags: ['Nederlands', 'soep', 'winter', 'traditioneel', 'rookworst'],
  },
  {
    id: 'pasta-e-fagioli',
    name: 'Pasta e Fagioli',
    description: 'Romige Italiaanse pasta met bonen soep. Vullend en voedzaam.',
    servings: 6,
    prepTime: 15,
    cookTime: 35,
    batchCookingScore: 4,
    freezerFriendly: true,
    fridgeLifeDays: 4,
    freezerLifeMonths: 2,
    ingredients: [
      { name: 'ui', amount: 1, unit: 'stuk', category: 'groenten', isPantryStaple: true },
      { name: 'wortel', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: false },
      { name: 'bleekselderij', amount: 2, unit: 'stengels', category: 'groenten', isPantryStaple: false },
      { name: 'knoflook', amount: 3, unit: 'tenen', category: 'groenten', isPantryStaple: true },
      { name: 'witte bonen', amount: 800, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'tomatenblokjes', amount: 400, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'groentebouillon', amount: 1, unit: 'liter', category: 'bouillon', isPantryStaple: true },
      { name: 'kleine pasta', amount: 150, unit: 'gram', category: 'pasta-rijst', isPantryStaple: false },
      { name: 'rozemarijn', amount: 1, unit: 'takje', category: 'kruiden', isPantryStaple: true },
    ],
    instructions: [
      'Snipper ui, wortel en selderij fijn.',
      'Fruit in olijfolie tot zacht.',
      'Voeg knoflook en rozemarijn toe.',
      'Pureer helft van de bonen en voeg toe met hele bonen.',
      'Giet bouillon en tomaten erbij.',
      'Kook 15 minuten.',
      'Voeg pasta toe en kook gaar.',
      'Serveer met Parmezaan en olijfolie.',
    ],
    variations: [
      { day: 1, suggestion: 'Met knapperig brood', extraIngredients: ['brood'] },
      { day: 2, suggestion: 'Met extra groenten', extraIngredients: ['spinazie'] },
      { day: 3, suggestion: 'Dikker ingekookt als pasta', extraIngredients: [] },
    ],
    tags: ['Italiaans', 'vegetarisch', 'soep', 'pasta', 'bonen'],
  },
  {
    id: 'shakshuka',
    name: 'Shakshuka',
    description: 'Gepocheerde eieren in kruidige tomatensaus. Perfect voor ontbijt of avondeten.',
    servings: 4,
    prepTime: 10,
    cookTime: 25,
    batchCookingScore: 2,
    freezerFriendly: false,
    fridgeLifeDays: 2,
    freezerLifeMonths: 0,
    ingredients: [
      { name: 'tomatenblokjes', amount: 800, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'paprika', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: false },
      { name: 'ui', amount: 1, unit: 'stuk', category: 'groenten', isPantryStaple: true },
      { name: 'knoflook', amount: 3, unit: 'tenen', category: 'groenten', isPantryStaple: true },
      { name: 'eieren', amount: 6, unit: 'stuks', category: 'zuivel', isPantryStaple: false },
      { name: 'komijn', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'paprikapoeder', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'feta', amount: 100, unit: 'gram', category: 'zuivel', isPantryStaple: false },
    ],
    instructions: [
      'Fruit ui en paprika tot zacht.',
      'Voeg knoflook en kruiden toe.',
      'Voeg tomaten toe en laat 10 minuten sudderen.',
      'Maak kuiltjes in de saus.',
      'Breek eieren in de kuiltjes.',
      'Dek af en pocheer 8-10 minuten.',
      'Verkruimel feta erover.',
      'Serveer uit de pan met brood.',
    ],
    variations: [
      { day: 1, suggestion: 'Met pitabrood', extraIngredients: ['pita'] },
      { day: 2, suggestion: 'Met chorizo', extraIngredients: ['chorizo'] },
    ],
    tags: ['Midden-Oosters', 'eieren', 'vegetarisch', 'ontbijt'],
  },
  {
    id: 'hutspot',
    name: 'Hutspot',
    description: 'Klassieke Nederlandse stamppot met wortel en ui. Simpel en smaakvol.',
    servings: 4,
    prepTime: 15,
    cookTime: 35,
    batchCookingScore: 3,
    freezerFriendly: false,
    fridgeLifeDays: 3,
    freezerLifeMonths: 0,
    ingredients: [
      { name: 'aardappelen', amount: 800, unit: 'gram', category: 'groenten', isPantryStaple: false },
      { name: 'winterwortel', amount: 500, unit: 'gram', category: 'groenten', isPantryStaple: false },
      { name: 'ui', amount: 3, unit: 'stuks', category: 'groenten', isPantryStaple: true },
      { name: 'boter', amount: 50, unit: 'gram', category: 'zuivel', isPantryStaple: true },
      { name: 'melk', amount: 100, unit: 'ml', category: 'zuivel', isPantryStaple: true },
      { name: 'runderstoofvlees', amount: 400, unit: 'gram', category: 'vlees', isPantryStaple: false },
    ],
    instructions: [
      'Schil en snijd aardappelen en wortels.',
      'Kook samen gaar in gezouten water (25 min).',
      'Snijd ui in grove stukken, kook mee laatste 10 minuten.',
      'Giet af en bewaar wat kookvocht.',
      'Stamp alles grof met boter en melk.',
      'Maak lekker smeuïg met kookvocht.',
      'Serveer met stoofvlees en jus.',
    ],
    variations: [
      { day: 1, suggestion: 'Met runderlappen', extraIngredients: ['runderlappen'] },
      { day: 2, suggestion: 'Met rookworst', extraIngredients: ['rookworst'] },
      { day: 3, suggestion: 'Restjes bakken als koekjes', extraIngredients: ['ei', 'paneermeel'] },
    ],
    tags: ['Nederlands', 'stamppot', 'traditioneel', 'wortel'],
  },
  {
    id: 'macaroni-ovenschotel',
    name: 'Macaroni Ovenschotel',
    description: 'Klassieke macaroni met kaassaus en ham. Favoriet bij jong en oud.',
    servings: 6,
    prepTime: 20,
    cookTime: 40,
    batchCookingScore: 4,
    freezerFriendly: true,
    fridgeLifeDays: 4,
    freezerLifeMonths: 2,
    ingredients: [
      { name: 'macaroni', amount: 400, unit: 'gram', category: 'pasta-rijst', isPantryStaple: false },
      { name: 'ham', amount: 200, unit: 'gram', category: 'vlees', isPantryStaple: false },
      { name: 'geraspte kaas', amount: 200, unit: 'gram', category: 'zuivel', isPantryStaple: false },
      { name: 'melk', amount: 500, unit: 'ml', category: 'zuivel', isPantryStaple: true },
      { name: 'boter', amount: 40, unit: 'gram', category: 'zuivel', isPantryStaple: true },
      { name: 'bloem', amount: 40, unit: 'gram', category: 'bakken', isPantryStaple: true },
      { name: 'champignons', amount: 200, unit: 'gram', category: 'groenten', isPantryStaple: false },
      { name: 'nootmuskaat', amount: 0.5, unit: 'tl', category: 'kruiden', isPantryStaple: true },
    ],
    instructions: [
      'Kook macaroni volgens verpakking.',
      'Maak een roux van boter en bloem.',
      'Voeg al roerend de melk toe.',
      'Roer helft van de kaas erdoor.',
      'Kruid met nootmuskaat, zout en peper.',
      'Meng pasta, saus, ham en champignons.',
      'Doe in ovenschaal, bestrooi met rest kaas.',
      'Gratineer 20 minuten op 200°C.',
    ],
    variations: [
      { day: 1, suggestion: 'Met salade', extraIngredients: ['sla', 'tomaat', 'komkommer'] },
      { day: 2, suggestion: 'Met extra groenten', extraIngredients: ['broccoli', 'paprika'] },
    ],
    tags: ['comfort food', 'pasta', 'oven', 'kaas'],
  },
  {
    id: 'bonen-chili',
    name: 'Bonen Chili (Vegetarisch)',
    description: 'Stevige vegetarische chili vol bonen en groenten. Even lekker als met vlees.',
    servings: 8,
    prepTime: 15,
    cookTime: 45,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 5,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'kidneybonen', amount: 400, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'zwarte bonen', amount: 400, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'tomatenblokjes', amount: 800, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'mais', amount: 200, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'ui', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: true },
      { name: 'paprika', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: false },
      { name: 'knoflook', amount: 3, unit: 'tenen', category: 'groenten', isPantryStaple: true },
      { name: 'komijn', amount: 2, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'chilivlokken', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
    ],
    instructions: [
      'Fruit ui en paprika.',
      'Voeg knoflook en kruiden toe.',
      'Voeg tomaten en bonen toe.',
      'Voeg mais toe.',
      'Laat 40 minuten sudderen.',
      'Breng op smaak.',
      'Serveer met toppings naar keuze.',
    ],
    variations: [
      { day: 1, suggestion: 'Met rijst en zure room', extraIngredients: ['rijst', 'zure room'] },
      { day: 2, suggestion: 'In taco\'s', extraIngredients: ['tacoschelpen', 'sla', 'kaas'] },
      { day: 3, suggestion: 'Over nacho\'s', extraIngredients: ['tortillachips', 'jalapeño'] },
      { day: 4, suggestion: 'In wraps', extraIngredients: ['wraps', 'guacamole'] },
    ],
    tags: ['vegetarisch', 'Mexicaans', 'bonen', 'budget'],
  },
  {
    id: 'kippensoep',
    name: 'Kippensoep',
    description: 'Troostende kippensoep met groenten en noedels. Goed voor lichaam en ziel.',
    servings: 8,
    prepTime: 20,
    cookTime: 60,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 4,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'kippenboutvlees', amount: 500, unit: 'gram', category: 'vlees', isPantryStaple: false },
      { name: 'wortel', amount: 3, unit: 'stuks', category: 'groenten', isPantryStaple: false },
      { name: 'bleekselderij', amount: 3, unit: 'stengels', category: 'groenten', isPantryStaple: false },
      { name: 'ui', amount: 1, unit: 'stuk', category: 'groenten', isPantryStaple: true },
      { name: 'prei', amount: 1, unit: 'stuk', category: 'groenten', isPantryStaple: false },
      { name: 'kippenbouillon', amount: 2, unit: 'liter', category: 'bouillon', isPantryStaple: true },
      { name: 'vermicelli', amount: 100, unit: 'gram', category: 'pasta-rijst', isPantryStaple: false },
      { name: 'laurierblad', amount: 2, unit: 'stuks', category: 'kruiden', isPantryStaple: true },
      { name: 'peterselie', amount: 3, unit: 'el', category: 'kruiden', isPantryStaple: false },
    ],
    instructions: [
      'Breng bouillon aan de kook met kip en laurier.',
      'Laat 30 minuten trekken.',
      'Haal kip eruit en trek in reepjes.',
      'Snijd groenten en voeg toe aan bouillon.',
      'Kook 15 minuten.',
      'Voeg vermicelli en kip terug.',
      'Kook nog 5 minuten.',
      'Garneer met peterselie.',
    ],
    variations: [
      { day: 1, suggestion: 'Met knapperig brood', extraIngredients: ['brood'] },
      { day: 2, suggestion: 'Met extra noedels', extraIngredients: ['noedels'] },
      { day: 3, suggestion: 'Als basis voor risotto', extraIngredients: ['risottorijst'] },
    ],
    tags: ['soep', 'kip', 'comfort food', 'gezond'],
  },
  {
    id: 'pompoensoep',
    name: 'Pompoensoep',
    description: 'Fluweelzachte pompoensoep met gember en kokos. Heerlijk in de herfst.',
    servings: 6,
    prepTime: 15,
    cookTime: 35,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 5,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'pompoen', amount: 1000, unit: 'gram', category: 'groenten', isPantryStaple: false },
      { name: 'ui', amount: 1, unit: 'stuk', category: 'groenten', isPantryStaple: true },
      { name: 'knoflook', amount: 2, unit: 'tenen', category: 'groenten', isPantryStaple: true },
      { name: 'gember', amount: 3, unit: 'cm', category: 'groenten', isPantryStaple: false },
      { name: 'kokosmelk', amount: 400, unit: 'ml', category: 'conserven', isPantryStaple: false },
      { name: 'groentebouillon', amount: 750, unit: 'ml', category: 'bouillon', isPantryStaple: true },
      { name: 'kerriepoeder', amount: 1, unit: 'el', category: 'kruiden', isPantryStaple: true },
    ],
    instructions: [
      'Schil pompoen en snijd in blokken.',
      'Fruit ui, knoflook en gember.',
      'Voeg kerriepoeder toe.',
      'Voeg pompoen en bouillon toe.',
      'Kook 25 minuten tot pompoen zacht is.',
      'Pureer glad.',
      'Roer kokosmelk erdoor.',
      'Breng op smaak.',
    ],
    variations: [
      { day: 1, suggestion: 'Met pompoenpitten en croutons', extraIngredients: ['pompoenpitten', 'brood'] },
      { day: 2, suggestion: 'Met een toef zure room', extraIngredients: ['zure room'] },
      { day: 3, suggestion: 'Met spekjes', extraIngredients: ['spek'] },
    ],
    tags: ['vegetarisch', 'soep', 'pompoen', 'herfst'],
  },
  {
    id: 'hachee',
    name: 'Hachee',
    description: 'Traditioneel Nederlands stoofgerecht met rundvlees. Wordt beter naarmate het langer staat.',
    servings: 6,
    prepTime: 20,
    cookTime: 180,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 5,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'runderstoofvlees', amount: 750, unit: 'gram', category: 'vlees', isPantryStaple: false },
      { name: 'ui', amount: 500, unit: 'gram', category: 'groenten', isPantryStaple: true },
      { name: 'bloem', amount: 3, unit: 'el', category: 'bakken', isPantryStaple: true },
      { name: 'runderbouillon', amount: 500, unit: 'ml', category: 'bouillon', isPantryStaple: true },
      { name: 'rode wijn', amount: 150, unit: 'ml', category: 'dranken', isPantryStaple: false },
      { name: 'azijn', amount: 2, unit: 'el', category: 'zuur', isPantryStaple: true },
      { name: 'laurierblad', amount: 2, unit: 'stuks', category: 'kruiden', isPantryStaple: true },
      { name: 'kruidnagel', amount: 2, unit: 'stuks', category: 'kruiden', isPantryStaple: true },
    ],
    instructions: [
      'Snijd vlees in blokken en bestrooi met bloem.',
      'Braad aan alle kanten bruin.',
      'Snipper uien en fruit tot goudbruin.',
      'Voeg vlees terug bij uien.',
      'Giet bouillon en wijn erbij.',
      'Voeg azijn, laurier en kruidnagel toe.',
      'Stoof 2,5-3 uur op laag vuur.',
      'Verwijder laurier en kruidnagel voor serveren.',
    ],
    variations: [
      { day: 1, suggestion: 'Met stamppot en rode kool', extraIngredients: ['aardappelen', 'rode kool'] },
      { day: 2, suggestion: 'Met aardappelpuree', extraIngredients: ['aardappelen', 'melk', 'boter'] },
      { day: 3, suggestion: 'Met brood', extraIngredients: ['brood'] },
    ],
    tags: ['Nederlands', 'rundvlees', 'stoofschotel', 'traditioneel'],
  },
  {
    id: 'vegetarische-lasagne',
    name: 'Vegetarische Lasagne',
    description: 'Rijke lasagne met spinazie en ricotta. Comfort food zonder vlees.',
    servings: 8,
    prepTime: 30,
    cookTime: 50,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 4,
    freezerLifeMonths: 2,
    ingredients: [
      { name: 'lasagnevellen', amount: 250, unit: 'gram', category: 'pasta-rijst', isPantryStaple: false },
      { name: 'spinazie', amount: 500, unit: 'gram', category: 'groenten', isPantryStaple: false },
      { name: 'ricotta', amount: 500, unit: 'gram', category: 'zuivel', isPantryStaple: false },
      { name: 'tomatenblokjes', amount: 800, unit: 'gram', category: 'conserven', isPantryStaple: false },
      { name: 'geraspte kaas', amount: 200, unit: 'gram', category: 'zuivel', isPantryStaple: false },
      { name: 'ui', amount: 1, unit: 'stuk', category: 'groenten', isPantryStaple: true },
      { name: 'knoflook', amount: 3, unit: 'tenen', category: 'groenten', isPantryStaple: true },
      { name: 'ei', amount: 1, unit: 'stuk', category: 'zuivel', isPantryStaple: true },
      { name: 'nootmuskaat', amount: 0.5, unit: 'tl', category: 'kruiden', isPantryStaple: true },
    ],
    instructions: [
      'Maak tomatensaus: fruit ui en knoflook, voeg tomaten toe.',
      'Laat 15 minuten inkoken.',
      'Meng ricotta met ei en nootmuskaat.',
      'Blancheer spinazie kort en meng door ricotta.',
      'Leg in ovenschaal: saus, vellen, ricottamix, herhaal.',
      'Eindig met saus en kaas.',
      'Bak 40-45 minuten op 180°C.',
      'Laat 10 minuten rusten voor het snijden.',
    ],
    variations: [
      { day: 1, suggestion: 'Met salade', extraIngredients: ['sla', 'tomaat'] },
      { day: 2, suggestion: 'Met knoflookbrood', extraIngredients: ['stokbrood', 'knoflookboter'] },
    ],
    tags: ['vegetarisch', 'Italiaans', 'oven', 'pasta', 'comfort food'],
  },
];

export function getRecipeById(id: string): Recipe | undefined {
  return recipes.find(r => r.id === id);
}

export function getAllRecipes(): Recipe[] {
  return recipes;
}
