import type { Offer } from './scraper';

// Get current week dates
function getValidDates(): { validFrom: string; validUntil: string } {
  const now = new Date();
  const dayOfWeek = now.getDay();
  const daysSinceMonday = dayOfWeek === 0 ? 6 : dayOfWeek - 1;

  const validFrom = new Date(now);
  validFrom.setDate(now.getDate() - daysSinceMonday);

  const validUntil = new Date(validFrom);
  validUntil.setDate(validFrom.getDate() + 6);

  return {
    validFrom: validFrom.toISOString().split('T')[0],
    validUntil: validUntil.toISOString().split('T')[0],
  };
}

const { validFrom, validUntil } = getValidDates();

export const sampleOffers: Offer[] = [
  // Albert Heijn offers
  {
    id: 'ah-rundergehakt-1',
    store: 'albert-heijn',
    productName: 'AH Rundergehakt 500g',
    originalPrice: 5.99,
    offerPrice: 3.99,
    discountPercentage: 33,
    category: 'vlees',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 3.99',
  },
  {
    id: 'ah-kipfilet-1',
    store: 'albert-heijn',
    productName: 'AH Kipfilet 450g',
    originalPrice: 6.49,
    offerPrice: 4.49,
    discountPercentage: 31,
    category: 'vlees',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: '1+1 GRATIS',
  },
  {
    id: 'ah-tomatenblokjes-1',
    store: 'albert-heijn',
    productName: 'AH Tomatenblokjes 400g',
    originalPrice: 1.29,
    offerPrice: 0.89,
    discountPercentage: 31,
    category: 'conserven',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 0.89',
  },
  {
    id: 'ah-kidneybonen-1',
    store: 'albert-heijn',
    productName: 'AH Kidneybonen 400g',
    originalPrice: 1.19,
    offerPrice: 0.79,
    discountPercentage: 34,
    category: 'conserven',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 0.79',
  },
  {
    id: 'ah-paprika-1',
    store: 'albert-heijn',
    productName: 'AH Paprika rood 3 stuks',
    originalPrice: 2.49,
    offerPrice: 1.49,
    discountPercentage: 40,
    category: 'groenten',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: '40% KORTING',
  },
  {
    id: 'ah-ui-1',
    store: 'albert-heijn',
    productName: 'AH Uien 1kg',
    originalPrice: 1.79,
    offerPrice: 0.99,
    discountPercentage: 45,
    category: 'groenten',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 0.99',
  },
  {
    id: 'ah-wortel-1',
    store: 'albert-heijn',
    productName: 'AH Wortelen 1kg',
    originalPrice: 1.49,
    offerPrice: 0.99,
    discountPercentage: 34,
    category: 'groenten',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 0.99',
  },
  {
    id: 'ah-aardappel-1',
    store: 'albert-heijn',
    productName: 'AH Kruimige aardappelen 2.5kg',
    originalPrice: 3.49,
    offerPrice: 2.49,
    discountPercentage: 29,
    category: 'groenten',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 2.49',
  },
  {
    id: 'ah-spaghetti-1',
    store: 'albert-heijn',
    productName: 'AH Spaghetti 500g',
    originalPrice: 1.29,
    offerPrice: 0.79,
    discountPercentage: 39,
    category: 'pasta-rijst',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 0.79',
  },
  {
    id: 'ah-rijst-1',
    store: 'albert-heijn',
    productName: 'AH Basmatirijst 1kg',
    originalPrice: 2.99,
    offerPrice: 1.99,
    discountPercentage: 33,
    category: 'pasta-rijst',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 1.99',
  },
  {
    id: 'ah-kokosmelk-1',
    store: 'albert-heijn',
    productName: 'AH Kokosmelk 400ml',
    originalPrice: 1.69,
    offerPrice: 0.99,
    discountPercentage: 41,
    category: 'conserven',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 0.99',
  },
  {
    id: 'ah-linzen-1',
    store: 'albert-heijn',
    productName: 'AH Rode linzen 500g',
    originalPrice: 2.29,
    offerPrice: 1.49,
    discountPercentage: 35,
    category: 'conserven',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 1.49',
  },
  {
    id: 'ah-kaas-1',
    store: 'albert-heijn',
    productName: 'AH Geraspte kaas 200g',
    originalPrice: 2.79,
    offerPrice: 1.99,
    discountPercentage: 29,
    category: 'zuivel',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 1.99',
  },
  {
    id: 'ah-spinazie-1',
    store: 'albert-heijn',
    productName: 'AH Spinazie 400g',
    originalPrice: 2.49,
    offerPrice: 1.49,
    discountPercentage: 40,
    category: 'groenten',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: '1+1 GRATIS',
  },
  {
    id: 'ah-rookworst-1',
    store: 'albert-heijn',
    productName: 'AH Rookworst 275g',
    originalPrice: 2.99,
    offerPrice: 1.99,
    discountPercentage: 33,
    category: 'vlees',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 1.99',
  },
  // Jumbo offers
  {
    id: 'jumbo-rundergehakt-1',
    store: 'jumbo',
    productName: 'Jumbo Rundergehakt 500g',
    originalPrice: 5.79,
    offerPrice: 3.49,
    discountPercentage: 40,
    category: 'vlees',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: '40% KORTING',
  },
  {
    id: 'jumbo-kipfilet-1',
    store: 'jumbo',
    productName: 'Jumbo Kipfilet 500g',
    originalPrice: 6.99,
    offerPrice: 4.99,
    discountPercentage: 29,
    category: 'vlees',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 4.99',
  },
  {
    id: 'jumbo-tomaat-1',
    store: 'jumbo',
    productName: 'Jumbo Gepelde tomaten 400g',
    originalPrice: 0.99,
    offerPrice: 0.69,
    discountPercentage: 30,
    category: 'conserven',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 0.69',
  },
  {
    id: 'jumbo-bonen-1',
    store: 'jumbo',
    productName: 'Jumbo Witte bonen 400g',
    originalPrice: 1.09,
    offerPrice: 0.69,
    discountPercentage: 37,
    category: 'conserven',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 0.69',
  },
  {
    id: 'jumbo-prei-1',
    store: 'jumbo',
    productName: 'Jumbo Prei 2 stuks',
    originalPrice: 1.99,
    offerPrice: 0.99,
    discountPercentage: 50,
    category: 'groenten',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: '1+1 GRATIS',
  },
  {
    id: 'jumbo-bleekselderij-1',
    store: 'jumbo',
    productName: 'Jumbo Bleekselderij',
    originalPrice: 1.49,
    offerPrice: 0.99,
    discountPercentage: 34,
    category: 'groenten',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 0.99',
  },
  {
    id: 'jumbo-courgette-1',
    store: 'jumbo',
    productName: 'Jumbo Courgette',
    originalPrice: 1.29,
    offerPrice: 0.79,
    discountPercentage: 39,
    category: 'groenten',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 0.79',
  },
  {
    id: 'jumbo-champignon-1',
    store: 'jumbo',
    productName: 'Jumbo Champignons 250g',
    originalPrice: 1.99,
    offerPrice: 1.29,
    discountPercentage: 35,
    category: 'groenten',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 1.29',
  },
  {
    id: 'jumbo-penne-1',
    store: 'jumbo',
    productName: 'Jumbo Penne 500g',
    originalPrice: 1.19,
    offerPrice: 0.69,
    discountPercentage: 42,
    category: 'pasta-rijst',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 0.69',
  },
  {
    id: 'jumbo-kikkererwten-1',
    store: 'jumbo',
    productName: 'Jumbo Kikkererwten 400g',
    originalPrice: 1.29,
    offerPrice: 0.79,
    discountPercentage: 39,
    category: 'conserven',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 0.79',
  },
  {
    id: 'jumbo-spliterwten-1',
    store: 'jumbo',
    productName: 'Jumbo Spliterwten 500g',
    originalPrice: 1.89,
    offerPrice: 1.19,
    discountPercentage: 37,
    category: 'conserven',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 1.19',
  },
  {
    id: 'jumbo-ham-1',
    store: 'jumbo',
    productName: 'Jumbo Achterham 150g',
    originalPrice: 2.49,
    offerPrice: 1.49,
    discountPercentage: 40,
    category: 'vlees',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: '40% KORTING',
  },
  {
    id: 'jumbo-ei-1',
    store: 'jumbo',
    productName: 'Jumbo Scharreleieren 10 stuks',
    originalPrice: 3.29,
    offerPrice: 2.29,
    discountPercentage: 30,
    category: 'zuivel',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: 'VOOR 2.29',
  },
  {
    id: 'jumbo-boerenkool-1',
    store: 'jumbo',
    productName: 'Jumbo Boerenkool 500g',
    originalPrice: 1.99,
    offerPrice: 0.99,
    discountPercentage: 50,
    category: 'groenten',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: '1+1 GRATIS',
  },
  {
    id: 'jumbo-pompoen-1',
    store: 'jumbo',
    productName: 'Jumbo Flespompoen per stuk',
    originalPrice: 2.49,
    offerPrice: 1.49,
    discountPercentage: 40,
    category: 'groenten',
    unit: 'per stuk',
    validFrom,
    validUntil,
    description: '40% KORTING',
  },
];
