import { saveRecipe } from '../database/recipes.js';
import type { Recipe } from '../../../shared/types.js';

const recipes: Recipe[] = [
  {
    id: 'chili-con-carne',
    name: 'Chili con Carne',
    description: 'Klassieke Mexicaanse stoofpot met gehakt en bonen. Perfect voor batch cooking, wordt alleen maar lekkerder!',
    servings: 8,
    prepTime: 20,
    cookTime: 60,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 5,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'rundergehakt', amount: 750, unit: 'g', category: 'vlees' },
      { name: 'kidneybonen', amount: 2, unit: 'blik', category: 'conserven' },
      { name: 'tomatenblokjes', amount: 2, unit: 'blik', category: 'conserven' },
      { name: 'ui', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: true },
      { name: 'knoflook', amount: 4, unit: 'teentjes', category: 'groenten', isPantryStaple: true },
      { name: 'paprika', amount: 2, unit: 'stuks', category: 'groenten' },
      { name: 'wortel', amount: 2, unit: 'stuks', category: 'groenten' },
      { name: 'tomatenpuree', amount: 2, unit: 'el', category: 'conserven', isPantryStaple: true },
      { name: 'komijn', amount: 2, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'paprikapoeder', amount: 2, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'cayennepeper', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
    ],
    instructions: [
      'Snipper de ui en hak de knoflook fijn. Snijd de paprika en wortel in blokjes.',
      'Verhit olie in een grote pan en bak het gehakt rul.',
      'Voeg ui en knoflook toe en bak 3 minuten mee.',
      'Voeg paprika, wortel en kruiden toe, bak 2 minuten.',
      'Voeg tomatenblokjes, tomatenpuree en bonen toe.',
      'Laat 45-60 minuten sudderen op laag vuur.',
      'Breng op smaak met zout en peper.',
    ],
    variationTips: [
      { day: 1, suggestion: 'Serveer met rijst en zure room', extraIngredients: ['rijst', 'zure room'] },
      { day: 2, suggestion: 'Op nachos met kaas', extraIngredients: ['nachos', 'geraspte kaas'] },
      { day: 3, suggestion: 'Als vulling voor wraps', extraIngredients: ['tortillawraps', 'sla', 'guacamole'] },
      { day: 4, suggestion: 'Op gepofte aardappel', extraIngredients: ['aardappel'] },
    ],
    tags: ['batch-cooking', 'stoofpot', 'gehakt', 'mexicaans'],
  },
  {
    id: 'bolognese-saus',
    name: 'Bolognese Saus',
    description: 'Rijke Italiaanse vleessaus die diep van smaak wordt. Maak een grote batch voor meerdere maaltijden.',
    servings: 10,
    prepTime: 25,
    cookTime: 90,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 5,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'rundergehakt', amount: 750, unit: 'g', category: 'vlees' },
      { name: 'varkensgehakt', amount: 250, unit: 'g', category: 'vlees' },
      { name: 'passata', amount: 700, unit: 'ml', category: 'conserven' },
      { name: 'tomatenblokjes', amount: 1, unit: 'blik', category: 'conserven' },
      { name: 'ui', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: true },
      { name: 'wortel', amount: 2, unit: 'stuks', category: 'groenten' },
      { name: 'selderij', amount: 2, unit: 'stengels', category: 'groenten' },
      { name: 'knoflook', amount: 4, unit: 'teentjes', category: 'groenten', isPantryStaple: true },
      { name: 'rode wijn', amount: 150, unit: 'ml', category: 'overig' },
      { name: 'melk', amount: 100, unit: 'ml', category: 'zuivel' },
      { name: 'oregano', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'laurierblad', amount: 2, unit: 'stuks', category: 'kruiden', isPantryStaple: true },
    ],
    instructions: [
      'Snijd ui, wortel en selderij in kleine blokjes (soffritto).',
      'Fruit de groenten in olijfolie tot ze zacht zijn.',
      'Voeg het gehakt toe en bak rul.',
      'Giet de wijn erbij en laat inkoken.',
      'Voeg passata, tomatenblokjes en kruiden toe.',
      'Voeg de melk toe en laat op laag vuur 1,5 uur sudderen.',
      'Roer af en toe en breng op smaak.',
    ],
    variationTips: [
      { day: 1, suggestion: 'Klassiek met spaghetti', extraIngredients: ['spaghetti', 'parmezaan'] },
      { day: 2, suggestion: 'Lasagne maken', extraIngredients: ['lasagnebladen', 'bechamelsaus', 'kaas'] },
      { day: 3, suggestion: 'Gevulde paprika', extraIngredients: ['paprika', 'rijst'] },
      { day: 4, suggestion: 'Met penne en groenten', extraIngredients: ['penne', 'courgette'] },
    ],
    tags: ['batch-cooking', 'italiaans', 'gehakt', 'pasta'],
  },
  {
    id: 'kipkerrie',
    name: 'Romige Kipkerrie',
    description: 'Mild gekruide curry met malse kip. Makkelijk te maken in grote hoeveelheden.',
    servings: 6,
    prepTime: 20,
    cookTime: 35,
    batchCookingScore: 4,
    freezerFriendly: true,
    fridgeLifeDays: 4,
    freezerLifeMonths: 2,
    ingredients: [
      { name: 'kipfilet', amount: 600, unit: 'g', category: 'vlees' },
      { name: 'ui', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: true },
      { name: 'knoflook', amount: 3, unit: 'teentjes', category: 'groenten', isPantryStaple: true },
      { name: 'gember', amount: 1, unit: 'el', category: 'groenten' },
      { name: 'kokosmelk', amount: 400, unit: 'ml', category: 'conserven' },
      { name: 'kippenbouillon', amount: 200, unit: 'ml', category: 'overig', isPantryStaple: true },
      { name: 'kerrie', amount: 3, unit: 'el', category: 'kruiden', isPantryStaple: true },
      { name: 'kurkuma', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'tomatenblokjes', amount: 1, unit: 'blik', category: 'conserven' },
      { name: 'paprika', amount: 1, unit: 'stuk', category: 'groenten' },
    ],
    instructions: [
      'Snijd de kip in blokjes en bak bruin in een grote pan.',
      'Haal de kip uit de pan en fruit de ui, knoflook en gember.',
      'Voeg kerrie en kurkuma toe, bak 1 minuut mee.',
      'Voeg kokosmelk, bouillon en tomatenblokjes toe.',
      'Breng aan de kook en voeg de kip weer toe.',
      'Laat 25 minuten sudderen tot de kip gaar is.',
      'Voeg paprika toe en kook nog 5 minuten.',
    ],
    variationTips: [
      { day: 1, suggestion: 'Met basmatirijst', extraIngredients: ['basmatirijst'] },
      { day: 2, suggestion: 'Met naanbrood', extraIngredients: ['naanbrood'] },
      { day: 3, suggestion: 'Op couscous met groenten', extraIngredients: ['couscous', 'spinazie'] },
    ],
    tags: ['batch-cooking', 'kip', 'curry', 'aziatisch'],
  },
  {
    id: 'linzensoep',
    name: 'Voedzame Linzensoep',
    description: 'Hartige soep boordevol eiwitten. Supergezond en heel goedkoop te maken.',
    servings: 8,
    prepTime: 15,
    cookTime: 40,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 5,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'rode linzen', amount: 400, unit: 'g', category: 'conserven' },
      { name: 'ui', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: true },
      { name: 'wortel', amount: 3, unit: 'stuks', category: 'groenten' },
      { name: 'selderij', amount: 3, unit: 'stengels', category: 'groenten' },
      { name: 'knoflook', amount: 4, unit: 'teentjes', category: 'groenten', isPantryStaple: true },
      { name: 'tomatenblokjes', amount: 1, unit: 'blik', category: 'conserven' },
      { name: 'groentebouillon', amount: 1.5, unit: 'liter', category: 'overig', isPantryStaple: true },
      { name: 'komijn', amount: 2, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'kurkuma', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'citroen', amount: 1, unit: 'stuk', category: 'fruit' },
    ],
    instructions: [
      'Snipper de ui en snijd wortel en selderij klein.',
      'Fruit de groenten in olijfolie tot ze zacht zijn.',
      'Voeg knoflook en kruiden toe, bak 1 minuut.',
      'Voeg linzen, tomaten en bouillon toe.',
      'Breng aan de kook en laat 35 minuten koken.',
      'Pureer de helft voor een romige textuur.',
      'Serveer met een scheut citroensap.',
    ],
    variationTips: [
      { day: 1, suggestion: 'Met knapperig brood', extraIngredients: ['stokbrood'] },
      { day: 2, suggestion: 'Met feta en peterselie', extraIngredients: ['feta', 'peterselie'] },
      { day: 3, suggestion: 'Met een klontje roomboter', extraIngredients: ['roomboter'] },
    ],
    tags: ['batch-cooking', 'soep', 'vegetarisch', 'goedkoop', 'gezond'],
  },
  {
    id: 'stamppot-boerenkool',
    name: 'Stamppot Boerenkool',
    description: 'Klassieke Nederlandse stamppot. Voedzaam, goedkoop en heerlijk in de winter.',
    servings: 6,
    prepTime: 20,
    cookTime: 30,
    batchCookingScore: 3,
    freezerFriendly: false,
    fridgeLifeDays: 3,
    freezerLifeMonths: 0,
    ingredients: [
      { name: 'aardappelen kruimig', amount: 1500, unit: 'g', category: 'groenten' },
      { name: 'boerenkool', amount: 500, unit: 'g', category: 'groenten' },
      { name: 'rookworst', amount: 2, unit: 'stuks', category: 'vlees' },
      { name: 'melk', amount: 150, unit: 'ml', category: 'zuivel' },
      { name: 'boter', amount: 50, unit: 'g', category: 'zuivel', isPantryStaple: true },
      { name: 'spekjes', amount: 150, unit: 'g', category: 'vlees' },
    ],
    instructions: [
      'Schil de aardappelen en kook ze gaar in gezouten water.',
      'Was de boerenkool en snijd fijn.',
      'Bak de spekjes knapperig uit.',
      'Giet de aardappelen af, bewaar wat kookvocht.',
      'Stamp de aardappelen met melk en boter.',
      'Roer de boerenkool door de stamp.',
      'Verwarm de rookworst in heet water.',
      'Serveer met rookworst, spekjes en jus.',
    ],
    variationTips: [
      { day: 1, suggestion: 'Klassiek met jus en mosterd', extraIngredients: ['jus', 'mosterd'] },
      { day: 2, suggestion: 'Opgebakken met een gebakken ei', extraIngredients: ['ei'] },
      { day: 3, suggestion: 'Als stamppotballetjes in de oven', extraIngredients: ['paneermeel', 'ei'] },
    ],
    tags: ['nederlands', 'stamppot', 'winter', 'comfort-food'],
  },
  {
    id: 'gehaktballetjes-tomatensaus',
    name: 'Gehaktballetjes in Tomatensaus',
    description: 'Italiaanse gehaktballetjes in rijke tomatensaus. Ideaal voor grote porties.',
    servings: 8,
    prepTime: 30,
    cookTime: 45,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 4,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'rundergehakt', amount: 750, unit: 'g', category: 'vlees' },
      { name: 'paneermeel', amount: 75, unit: 'g', category: 'overig' },
      { name: 'ei', amount: 1, unit: 'stuk', category: 'zuivel' },
      { name: 'parmezaan', amount: 50, unit: 'g', category: 'zuivel' },
      { name: 'passata', amount: 800, unit: 'ml', category: 'conserven' },
      { name: 'tomatenblokjes', amount: 1, unit: 'blik', category: 'conserven' },
      { name: 'ui', amount: 1, unit: 'stuk', category: 'groenten', isPantryStaple: true },
      { name: 'knoflook', amount: 4, unit: 'teentjes', category: 'groenten', isPantryStaple: true },
      { name: 'basilicum', amount: 1, unit: 'bosje', category: 'kruiden' },
      { name: 'oregano', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
    ],
    instructions: [
      'Meng gehakt met paneermeel, ei, helft parmezaan, zout en peper.',
      'Rol balletjes van ongeveer 3cm.',
      'Bak de balletjes rondom bruin in olijfolie.',
      'Fruit ui en knoflook in dezelfde pan.',
      'Voeg passata, tomatenblokjes en kruiden toe.',
      'Leg de balletjes in de saus en laat 30 min sudderen.',
      'Serveer met verse basilicum en parmezaan.',
    ],
    variationTips: [
      { day: 1, suggestion: 'Met spaghetti', extraIngredients: ['spaghetti'] },
      { day: 2, suggestion: 'In een broodje (meatball sub)', extraIngredients: ['ciabatta', 'mozzarella'] },
      { day: 3, suggestion: 'Met polenta', extraIngredients: ['polenta'] },
      { day: 4, suggestion: 'Op rijst met groenten', extraIngredients: ['rijst', 'broccoli'] },
    ],
    tags: ['batch-cooking', 'italiaans', 'gehakt', 'comfort-food'],
  },
  {
    id: 'minestrone-soep',
    name: 'Minestrone Soep',
    description: 'Rijke Italiaanse groentesoep met pasta en bonen. Heel voedzaam en budgetvriendelijk.',
    servings: 8,
    prepTime: 20,
    cookTime: 40,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 5,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'witte bonen', amount: 1, unit: 'blik', category: 'conserven' },
      { name: 'tomatenblokjes', amount: 2, unit: 'blik', category: 'conserven' },
      { name: 'kleine pasta', amount: 150, unit: 'g', category: 'pasta-rijst' },
      { name: 'courgette', amount: 1, unit: 'stuk', category: 'groenten' },
      { name: 'wortel', amount: 2, unit: 'stuks', category: 'groenten' },
      { name: 'selderij', amount: 2, unit: 'stengels', category: 'groenten' },
      { name: 'ui', amount: 1, unit: 'stuk', category: 'groenten', isPantryStaple: true },
      { name: 'knoflook', amount: 3, unit: 'teentjes', category: 'groenten', isPantryStaple: true },
      { name: 'groentebouillon', amount: 1.5, unit: 'liter', category: 'overig', isPantryStaple: true },
      { name: 'spinazie', amount: 100, unit: 'g', category: 'groenten' },
      { name: 'parmezaan', amount: 50, unit: 'g', category: 'zuivel' },
    ],
    instructions: [
      'Snipper ui en snijd alle groenten in blokjes.',
      'Fruit de ui en knoflook in olijfolie.',
      'Voeg wortel en selderij toe, bak 5 minuten.',
      'Voeg bouillon, tomaten en bonen toe.',
      'Kook 20 minuten en voeg dan pasta en courgette toe.',
      'Kook nog 10 minuten tot pasta gaar is.',
      'Roer spinazie erdoor en serveer met parmezaan.',
    ],
    variationTips: [
      { day: 1, suggestion: 'Met knapperig brood', extraIngredients: ['stokbrood'] },
      { day: 2, suggestion: 'Met extra pesto', extraIngredients: ['pesto'] },
      { day: 3, suggestion: 'Met een klontje roomkaas', extraIngredients: ['roomkaas'] },
    ],
    tags: ['batch-cooking', 'soep', 'italiaans', 'vegetarisch'],
  },
  {
    id: 'dhal',
    name: 'Indiase Dhal',
    description: 'Romige linzencurry uit India. Extreem goedkoop en vol eiwitten.',
    servings: 6,
    prepTime: 15,
    cookTime: 35,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 5,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'rode linzen', amount: 300, unit: 'g', category: 'conserven' },
      { name: 'ui', amount: 1, unit: 'stuk', category: 'groenten', isPantryStaple: true },
      { name: 'knoflook', amount: 4, unit: 'teentjes', category: 'groenten', isPantryStaple: true },
      { name: 'gember', amount: 2, unit: 'el', category: 'groenten' },
      { name: 'tomatenblokjes', amount: 1, unit: 'blik', category: 'conserven' },
      { name: 'kokosmelk', amount: 200, unit: 'ml', category: 'conserven' },
      { name: 'kurkuma', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'komijn', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'garam masala', amount: 2, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'spinazie', amount: 100, unit: 'g', category: 'groenten' },
    ],
    instructions: [
      'Fruit ui, knoflook en gember in olie.',
      'Voeg kurkuma, komijn en garam masala toe.',
      'Voeg linzen, tomaten en 400ml water toe.',
      'Kook 25-30 minuten tot de linzen zacht zijn.',
      'Roer de kokosmelk erdoor.',
      'Voeg spinazie toe en laat slinken.',
      'Breng op smaak met zout en serveer.',
    ],
    variationTips: [
      { day: 1, suggestion: 'Met basmatirijst', extraIngredients: ['basmatirijst'] },
      { day: 2, suggestion: 'Met naanbrood', extraIngredients: ['naanbrood'] },
      { day: 3, suggestion: 'Met chapati en raita', extraIngredients: ['chapati', 'yoghurt', 'komkommer'] },
    ],
    tags: ['batch-cooking', 'indiaas', 'vegetarisch', 'vegan', 'goedkoop'],
  },
  {
    id: 'pulled-pork',
    name: 'Pulled Pork',
    description: 'Langzaam gegaard varkensvlees dat uit elkaar valt. Perfect voor grote groepen.',
    servings: 10,
    prepTime: 20,
    cookTime: 360,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 5,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'varkensschouder', amount: 2000, unit: 'g', category: 'vlees' },
      { name: 'ui', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: true },
      { name: 'knoflook', amount: 6, unit: 'teentjes', category: 'groenten', isPantryStaple: true },
      { name: 'tomatenketchup', amount: 200, unit: 'ml', category: 'sauzen' },
      { name: 'appelazijn', amount: 100, unit: 'ml', category: 'overig' },
      { name: 'bruine suiker', amount: 100, unit: 'g', category: 'overig' },
      { name: 'paprikapoeder', amount: 2, unit: 'el', category: 'kruiden', isPantryStaple: true },
      { name: 'komijn', amount: 1, unit: 'el', category: 'kruiden', isPantryStaple: true },
      { name: 'kippenbouillon', amount: 250, unit: 'ml', category: 'overig', isPantryStaple: true },
    ],
    instructions: [
      'Meng alle kruiden en wrijf het vlees ermee in.',
      'Leg de uien op de bodem van een braadpan.',
      'Leg het vlees erop en giet de bouillon erbij.',
      'Dek af en bak 5-6 uur op 150°C.',
      'Meng ketchup, azijn en suiker voor de BBQ-saus.',
      'Trek het vlees uit elkaar met twee vorken.',
      'Meng met de BBQ-saus en serveer.',
    ],
    variationTips: [
      { day: 1, suggestion: 'In briochebroodjes met coleslaw', extraIngredients: ['briochebol', 'koolsla'] },
      { day: 2, suggestion: "In taco's met guacamole", extraIngredients: ['tacoschelpen', 'guacamole', 'zure room'] },
      { day: 3, suggestion: 'Op rijst met groenten', extraIngredients: ['rijst', 'paprika'] },
      { day: 4, suggestion: 'Als topping op nachos', extraIngredients: ['nachos', 'kaas', 'jalapeno'] },
    ],
    tags: ['batch-cooking', 'slow-cooker', 'amerikaans', 'vlees'],
  },
  {
    id: 'groentecurry',
    name: 'Thaise Groentecurry',
    description: 'Snelle en voedzame curry vol groenten. Makkelijk aan te passen aan wat in de aanbieding is.',
    servings: 6,
    prepTime: 15,
    cookTime: 25,
    batchCookingScore: 4,
    freezerFriendly: true,
    fridgeLifeDays: 4,
    freezerLifeMonths: 2,
    ingredients: [
      { name: 'kokosmelk', amount: 400, unit: 'ml', category: 'conserven' },
      { name: 'groene currypasta', amount: 3, unit: 'el', category: 'sauzen' },
      { name: 'broccoli', amount: 300, unit: 'g', category: 'groenten' },
      { name: 'paprika', amount: 2, unit: 'stuks', category: 'groenten' },
      { name: 'courgette', amount: 1, unit: 'stuk', category: 'groenten' },
      { name: 'champignons', amount: 200, unit: 'g', category: 'groenten' },
      { name: 'spinazie', amount: 100, unit: 'g', category: 'groenten' },
      { name: 'vissaus', amount: 2, unit: 'el', category: 'sauzen' },
      { name: 'limoen', amount: 1, unit: 'stuk', category: 'fruit' },
    ],
    instructions: [
      'Snijd alle groenten in hapklare stukken.',
      'Verhit een scheutje olie en bak de currypasta 1 minuut.',
      'Voeg de kokosmelk toe en roer goed.',
      'Voeg de groenten toe, begin met de hardste.',
      'Laat 15-20 minuten sudderen.',
      'Breng op smaak met vissaus en limoensap.',
      'Serveer met verse koriander.',
    ],
    variationTips: [
      { day: 1, suggestion: 'Met jasmijnrijst', extraIngredients: ['jasmijnrijst'] },
      { day: 2, suggestion: 'Met noedels', extraIngredients: ['rijstnoedels'] },
      { day: 3, suggestion: 'Met gebakken tofu', extraIngredients: ['tofu'] },
    ],
    tags: ['batch-cooking', 'vegetarisch', 'thais', 'snel'],
  },
  {
    id: 'erwtensoep',
    name: 'Hollandse Erwtensoep',
    description: 'De klassieker onder de Nederlandse wintergerechten. Wordt de dag erna nog lekkerder!',
    servings: 10,
    prepTime: 30,
    cookTime: 120,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 5,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'spliterwten', amount: 500, unit: 'g', category: 'conserven' },
      { name: 'rookworst', amount: 2, unit: 'stuks', category: 'vlees' },
      { name: 'spekblokjes', amount: 150, unit: 'g', category: 'vlees' },
      { name: 'prei', amount: 2, unit: 'stuks', category: 'groenten' },
      { name: 'wortel', amount: 3, unit: 'stuks', category: 'groenten' },
      { name: 'selderij', amount: 3, unit: 'stengels', category: 'groenten' },
      { name: 'aardappelen', amount: 500, unit: 'g', category: 'groenten' },
      { name: 'ui', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: true },
    ],
    instructions: [
      'Spoel de erwten en kook ze 1 uur in ruim water.',
      'Voeg aardappelen, wortel, selderij en ui toe.',
      'Kook nog 45 minuten.',
      'Voeg prei en spekblokjes toe.',
      'Kook nog 15 minuten tot alles zacht is.',
      'Snijd de rookworst in plakken.',
      'Serveer met roggebrood en katenspek.',
    ],
    variationTips: [
      { day: 1, suggestion: 'Met roggebrood en katenspek', extraIngredients: ['roggebrood', 'katenspek'] },
      { day: 2, suggestion: 'Opnieuw opgewarmd (nog lekkerder!)', extraIngredients: [] },
      { day: 3, suggestion: 'Met extra mosterd', extraIngredients: ['mosterd'] },
    ],
    tags: ['batch-cooking', 'soep', 'nederlands', 'winter'],
  },
  {
    id: 'pasta-e-fagioli',
    name: 'Pasta e Fagioli',
    description: 'Italiaanse pasta-bonensoep. Simpel, voedzaam en goedkoop.',
    servings: 6,
    prepTime: 15,
    cookTime: 35,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 4,
    freezerLifeMonths: 2,
    ingredients: [
      { name: 'witte bonen', amount: 2, unit: 'blik', category: 'conserven' },
      { name: 'kleine pasta', amount: 200, unit: 'g', category: 'pasta-rijst' },
      { name: 'tomatenblokjes', amount: 1, unit: 'blik', category: 'conserven' },
      { name: 'ui', amount: 1, unit: 'stuk', category: 'groenten', isPantryStaple: true },
      { name: 'wortel', amount: 2, unit: 'stuks', category: 'groenten' },
      { name: 'selderij', amount: 2, unit: 'stengels', category: 'groenten' },
      { name: 'knoflook', amount: 4, unit: 'teentjes', category: 'groenten', isPantryStaple: true },
      { name: 'groentebouillon', amount: 1, unit: 'liter', category: 'overig', isPantryStaple: true },
      { name: 'parmezaan', amount: 50, unit: 'g', category: 'zuivel' },
      { name: 'rozemarijn', amount: 1, unit: 'takje', category: 'kruiden' },
    ],
    instructions: [
      'Snijd ui, wortel en selderij fijn.',
      'Fruit in olijfolie tot zacht.',
      'Voeg knoflook en rozemarijn toe.',
      'Voeg tomaten, bonen en bouillon toe.',
      'Kook 20 minuten en voeg dan pasta toe.',
      'Kook nog 10 minuten tot pasta gaar is.',
      'Serveer met veel parmezaan.',
    ],
    variationTips: [
      { day: 1, suggestion: 'Met knapperig brood', extraIngredients: ['ciabatta'] },
      { day: 2, suggestion: 'Met extra groenten', extraIngredients: ['spinazie'] },
    ],
    tags: ['batch-cooking', 'soep', 'italiaans', 'vegetarisch', 'goedkoop'],
  },
  {
    id: 'shakshuka',
    name: 'Shakshuka',
    description: 'Eieren gepocheerd in pittige tomatensaus. Perfect voor ontbijt, lunch of avondeten.',
    servings: 4,
    prepTime: 10,
    cookTime: 25,
    batchCookingScore: 3,
    freezerFriendly: false,
    fridgeLifeDays: 2,
    freezerLifeMonths: 0,
    ingredients: [
      { name: 'tomatenblokjes', amount: 2, unit: 'blik', category: 'conserven' },
      { name: 'eieren', amount: 6, unit: 'stuks', category: 'zuivel' },
      { name: 'ui', amount: 1, unit: 'stuk', category: 'groenten', isPantryStaple: true },
      { name: 'paprika', amount: 1, unit: 'stuk', category: 'groenten' },
      { name: 'knoflook', amount: 3, unit: 'teentjes', category: 'groenten', isPantryStaple: true },
      { name: 'komijn', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'paprikapoeder', amount: 1, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'feta', amount: 100, unit: 'g', category: 'zuivel' },
    ],
    instructions: [
      'Fruit ui en paprika in olijfolie.',
      'Voeg knoflook en kruiden toe.',
      'Voeg tomatenblokjes toe en laat 15 min sudderen.',
      'Maak kuiltjes en breek de eieren erin.',
      'Dek af en kook tot de eieren gestold zijn.',
      'Verkruimel feta erover.',
      'Serveer met vers brood.',
    ],
    variationTips: [
      { day: 1, suggestion: 'Met pita of Turks brood', extraIngredients: ['pitabrood'] },
      { day: 2, suggestion: 'Met extra groenten', extraIngredients: ['spinazie'] },
    ],
    tags: ['snel', 'vegetarisch', 'midden-oosten', 'eieren'],
  },
  {
    id: 'stamppot-hutspot',
    name: 'Hutspot',
    description: 'Nederlandse stamppot met wortel en ui. Klassiek comfort food.',
    servings: 6,
    prepTime: 20,
    cookTime: 35,
    batchCookingScore: 3,
    freezerFriendly: false,
    fridgeLifeDays: 3,
    freezerLifeMonths: 0,
    ingredients: [
      { name: 'aardappelen kruimig', amount: 1200, unit: 'g', category: 'groenten' },
      { name: 'wortel', amount: 500, unit: 'g', category: 'groenten' },
      { name: 'ui', amount: 3, unit: 'stuks', category: 'groenten', isPantryStaple: true },
      { name: 'runderstoofvlees', amount: 500, unit: 'g', category: 'vlees' },
      { name: 'boter', amount: 50, unit: 'g', category: 'zuivel', isPantryStaple: true },
      { name: 'melk', amount: 100, unit: 'ml', category: 'zuivel' },
    ],
    instructions: [
      'Schil aardappelen en wortel, snijd in stukken.',
      'Snijd de uien in ringen.',
      'Kook alles samen gaar in gezouten water.',
      'Bereid het stoofvlees volgens verpakking.',
      'Giet de groenten af, bewaar wat vocht.',
      'Stamp met boter en melk.',
      'Serveer met het stoofvlees en jus.',
    ],
    variationTips: [
      { day: 1, suggestion: 'Met stoofvlees en jus', extraIngredients: ['jus'] },
      { day: 2, suggestion: 'Opgebakken met spiegelei', extraIngredients: ['ei'] },
    ],
    tags: ['nederlands', 'stamppot', 'comfort-food'],
  },
  {
    id: 'macaroni-kaassaus',
    name: 'Macaroni met Kaassaus',
    description: 'Klassieke mac and cheese. Simpel maar heerlijk comfort food.',
    servings: 6,
    prepTime: 10,
    cookTime: 20,
    batchCookingScore: 3,
    freezerFriendly: true,
    fridgeLifeDays: 4,
    freezerLifeMonths: 2,
    ingredients: [
      { name: 'macaroni', amount: 400, unit: 'g', category: 'pasta-rijst' },
      { name: 'geraspte kaas', amount: 300, unit: 'g', category: 'zuivel' },
      { name: 'melk', amount: 400, unit: 'ml', category: 'zuivel' },
      { name: 'boter', amount: 40, unit: 'g', category: 'zuivel', isPantryStaple: true },
      { name: 'bloem', amount: 40, unit: 'g', category: 'overig', isPantryStaple: true },
      { name: 'nootmuskaat', amount: 0.5, unit: 'tl', category: 'kruiden', isPantryStaple: true },
    ],
    instructions: [
      'Kook de macaroni volgens de verpakking.',
      'Smelt de boter en roer de bloem erdoor.',
      'Voeg langzaam de melk toe al roerend.',
      'Kook tot een gladde saus.',
      'Haal van het vuur en roer de kaas erdoor.',
      'Meng de saus door de pasta.',
      'Breng op smaak met nootmuskaat, zout en peper.',
    ],
    variationTips: [
      { day: 1, suggestion: 'Met broccoli en ham', extraIngredients: ['broccoli', 'ham'] },
      { day: 2, suggestion: 'Gegratineerd in de oven', extraIngredients: ['paneermeel'] },
      { day: 3, suggestion: 'Met gebakken spekjes', extraIngredients: ['spekjes'] },
    ],
    tags: ['snel', 'comfort-food', 'pasta', 'vegetarisch'],
  },
  {
    id: 'bonen-chili',
    name: 'Vegetarische Bonen Chili',
    description: 'Hartige vegetarische chili boordevol bonen. Net zo voedzaam als de vleesvariant.',
    servings: 8,
    prepTime: 15,
    cookTime: 45,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 5,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'kidneybonen', amount: 2, unit: 'blik', category: 'conserven' },
      { name: 'zwarte bonen', amount: 1, unit: 'blik', category: 'conserven' },
      { name: 'kikkererwten', amount: 1, unit: 'blik', category: 'conserven' },
      { name: 'tomatenblokjes', amount: 2, unit: 'blik', category: 'conserven' },
      { name: 'ui', amount: 2, unit: 'stuks', category: 'groenten', isPantryStaple: true },
      { name: 'paprika', amount: 2, unit: 'stuks', category: 'groenten' },
      { name: 'knoflook', amount: 4, unit: 'teentjes', category: 'groenten', isPantryStaple: true },
      { name: 'mais', amount: 1, unit: 'blik', category: 'conserven' },
      { name: 'komijn', amount: 2, unit: 'tl', category: 'kruiden', isPantryStaple: true },
      { name: 'chipotle', amount: 1, unit: 'tl', category: 'kruiden' },
    ],
    instructions: [
      'Snipper de ui en hak de knoflook.',
      'Snijd de paprika in blokjes.',
      'Fruit ui en knoflook in olie.',
      'Voeg paprika en kruiden toe.',
      'Voeg alle bonen en tomaten toe.',
      'Laat 40 minuten sudderen.',
      'Voeg mais toe en warm door.',
      'Serveer met toppings naar keuze.',
    ],
    variationTips: [
      { day: 1, suggestion: 'Met rijst en zure room', extraIngredients: ['rijst', 'zure room'] },
      { day: 2, suggestion: 'Op nachos met kaas', extraIngredients: ['nachos', 'kaas'] },
      { day: 3, suggestion: 'In wraps met guacamole', extraIngredients: ['tortillawraps', 'guacamole'] },
    ],
    tags: ['batch-cooking', 'vegetarisch', 'vegan', 'mexicaans', 'goedkoop'],
  },
  {
    id: 'kippensoep',
    name: 'Oma\'s Kippensoep',
    description: 'Voedzame kippensoep zoals oma hem maakte. Goed voor wat je scheelt!',
    servings: 8,
    prepTime: 20,
    cookTime: 60,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 4,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'kippenpoten', amount: 4, unit: 'stuks', category: 'vlees' },
      { name: 'wortel', amount: 3, unit: 'stuks', category: 'groenten' },
      { name: 'selderij', amount: 3, unit: 'stengels', category: 'groenten' },
      { name: 'prei', amount: 1, unit: 'stuk', category: 'groenten' },
      { name: 'ui', amount: 1, unit: 'stuk', category: 'groenten', isPantryStaple: true },
      { name: 'vermicelli', amount: 100, unit: 'g', category: 'pasta-rijst' },
      { name: 'laurierblad', amount: 2, unit: 'stuks', category: 'kruiden', isPantryStaple: true },
      { name: 'peterselie', amount: 1, unit: 'bosje', category: 'kruiden' },
    ],
    instructions: [
      'Kook de kippenpoten in 2 liter water.',
      'Schep het schuim eraf.',
      'Voeg ui en laurierblad toe, kook 45 min.',
      'Haal de kip eruit en trek het vlees los.',
      'Snijd wortel, selderij en prei.',
      'Voeg groenten aan de bouillon toe.',
      'Kook 15 min en voeg vermicelli toe.',
      'Voeg het kipvlees weer toe.',
      'Garneer met peterselie.',
    ],
    variationTips: [
      { day: 1, suggestion: 'Met vers brood', extraIngredients: ['brood'] },
      { day: 2, suggestion: 'Met extra noedels', extraIngredients: ['noedels'] },
    ],
    tags: ['batch-cooking', 'soep', 'kip', 'comfort-food'],
  },
  {
    id: 'pompoensoep',
    name: 'Romige Pompoensoep',
    description: 'Fluweelzachte soep perfect voor de herfst. Pompoen is vaak in de aanbieding!',
    servings: 6,
    prepTime: 15,
    cookTime: 35,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 5,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'pompoen', amount: 1000, unit: 'g', category: 'groenten' },
      { name: 'ui', amount: 1, unit: 'stuk', category: 'groenten', isPantryStaple: true },
      { name: 'knoflook', amount: 2, unit: 'teentjes', category: 'groenten', isPantryStaple: true },
      { name: 'groentebouillon', amount: 800, unit: 'ml', category: 'overig', isPantryStaple: true },
      { name: 'kokosmelk', amount: 200, unit: 'ml', category: 'conserven' },
      { name: 'gember', amount: 1, unit: 'el', category: 'groenten' },
      { name: 'pompoenpitten', amount: 50, unit: 'g', category: 'overig' },
    ],
    instructions: [
      'Snijd pompoen in blokken (schil mag eraf).',
      'Fruit ui, knoflook en gember.',
      'Voeg pompoen en bouillon toe.',
      'Kook 25-30 minuten tot zacht.',
      'Pureer glad met een staafmixer.',
      'Roer de kokosmelk erdoor.',
      'Serveer met geroosterde pompoenpitten.',
    ],
    variationTips: [
      { day: 1, suggestion: 'Met knapperig brood', extraIngredients: ['brood'] },
      { day: 2, suggestion: 'Met een toef creme fraiche', extraIngredients: ['creme fraiche'] },
    ],
    tags: ['batch-cooking', 'soep', 'vegetarisch', 'herfst'],
  },
  {
    id: 'hachee',
    name: 'Nederlandse Hachee',
    description: 'Stoofpot van rundvlees in rijke jus. Een echte Nederlandse klassieker.',
    servings: 6,
    prepTime: 25,
    cookTime: 150,
    batchCookingScore: 5,
    freezerFriendly: true,
    fridgeLifeDays: 5,
    freezerLifeMonths: 3,
    ingredients: [
      { name: 'runderstoofvlees', amount: 800, unit: 'g', category: 'vlees' },
      { name: 'ui', amount: 4, unit: 'stuks', category: 'groenten', isPantryStaple: true },
      { name: 'runderbouillon', amount: 500, unit: 'ml', category: 'overig', isPantryStaple: true },
      { name: 'laurierblad', amount: 3, unit: 'stuks', category: 'kruiden', isPantryStaple: true },
      { name: 'kruidnagel', amount: 4, unit: 'stuks', category: 'kruiden' },
      { name: 'appelstroop', amount: 2, unit: 'el', category: 'overig' },
      { name: 'witte wijnazijn', amount: 2, unit: 'el', category: 'overig', isPantryStaple: true },
    ],
    instructions: [
      'Snijd het vlees in blokken.',
      'Braad het vlees rondom bruin.',
      'Haal eruit en fruit de uiringen.',
      'Leg het vlees terug en voeg bouillon toe.',
      'Voeg laurier, kruidnagel en appelstroop toe.',
      'Stoof 2-2,5 uur op laag vuur.',
      'Voeg azijn toe voor de finishing touch.',
    ],
    variationTips: [
      { day: 1, suggestion: 'Met aardappelpuree en rodekool', extraIngredients: ['aardappelen', 'rodekool'] },
      { day: 2, suggestion: 'Met stamppot', extraIngredients: ['aardappelen', 'boerenkool'] },
    ],
    tags: ['batch-cooking', 'stoofpot', 'nederlands', 'rundvlees'],
  },
  {
    id: 'vegetarische-lasagne',
    name: 'Vegetarische Lasagne',
    description: 'Rijke lasagne vol groenten. Makkelijk te maken voor een grote groep.',
    servings: 8,
    prepTime: 30,
    cookTime: 50,
    batchCookingScore: 4,
    freezerFriendly: true,
    fridgeLifeDays: 4,
    freezerLifeMonths: 2,
    ingredients: [
      { name: 'lasagnebladen', amount: 250, unit: 'g', category: 'pasta-rijst' },
      { name: 'spinazie', amount: 400, unit: 'g', category: 'groenten' },
      { name: 'ricotta', amount: 250, unit: 'g', category: 'zuivel' },
      { name: 'mozzarella', amount: 250, unit: 'g', category: 'zuivel' },
      { name: 'passata', amount: 700, unit: 'ml', category: 'conserven' },
      { name: 'courgette', amount: 1, unit: 'stuk', category: 'groenten' },
      { name: 'champignons', amount: 200, unit: 'g', category: 'groenten' },
      { name: 'ui', amount: 1, unit: 'stuk', category: 'groenten', isPantryStaple: true },
      { name: 'knoflook', amount: 3, unit: 'teentjes', category: 'groenten', isPantryStaple: true },
      { name: 'parmezaan', amount: 50, unit: 'g', category: 'zuivel' },
    ],
    instructions: [
      'Bak ui, knoflook, courgette en champignons.',
      'Voeg spinazie toe en laat slinken.',
      'Meng ricotta met de groenten.',
      'Leg een laag passata op de bodem.',
      'Bouw lagen: pasta, groentenmix, mozzarella.',
      'Eindig met passata en parmezaan.',
      'Bak 45 min op 180°C.',
    ],
    variationTips: [
      { day: 1, suggestion: 'Met salade en knoflookbrood', extraIngredients: ['sla', 'knoflookbrood'] },
      { day: 2, suggestion: 'Opgewarmd met extra kaas', extraIngredients: ['kaas'] },
    ],
    tags: ['batch-cooking', 'italiaans', 'vegetarisch', 'pasta'],
  },
];

async function seed() {
  console.log('Seeding recipes...');

  for (const recipe of recipes) {
    console.log(`Adding: ${recipe.name}`);
    saveRecipe(recipe);
  }

  console.log(`\nSeeded ${recipes.length} recipes successfully!`);
}

seed().catch(console.error);
